In [ ]:
# 1) Replace Nan with 0 and Interchange 3 rows and 3 columns of 2D array [[6, -8, 73, -110], [np.nan, -8, 0, 94]] 
# 2) Move axes of 3D array to new positions 
# 3) Replace NaN values with average of columns 
# 4) Replace negative value with zero in numpy array using replace
# 5) Study the following program import numpy as np 
# # create a numpy 1d-arrays arr1 = np.array([3, 4]) arr2 = np.array([1, 0])
# #  # find average of NumPy arrays avg = (arr1 + arr2) / 2 print("Average of NumPy arrays:\n", avg) 
# # -> Calculate average mean median mode values of two NumPy 2d-arrays
# 6) Solve the following equation using linalg() and inverse Matrix method x - 2y + 3z = 9 -x + 3y - z = -6 2x - 5y + 5z = 17 7) 
# Using "Customizing Matplotlib Visualizations"discussed in Numpy session4 notes plot graph to compare your at least 2 semester result

In [6]:
import numpy as np
arr = np.array([
    [1,2,3,np.nan,5],
    [np.nan, -2, 5, 0,-7]
])

print(arr,"\n")

arr = np.nan_to_num(arr, nan=0)
print(arr,"\n")

arr_transpose = arr.transpose()
print(arr_transpose)

[[ 1.  2.  3. nan  5.]
 [nan -2.  5.  0. -7.]] 

[[ 1.  2.  3.  0.  5.]
 [ 0. -2.  5.  0. -7.]] 

[[ 1.  0.]
 [ 2. -2.]
 [ 3.  5.]
 [ 0.  0.]
 [ 5. -7.]]


In [10]:
import numpy as np
a = np.arange(24).reshape(2,3,4)
print(a.shape,"\n")

arr = np.moveaxis(a,0,2)
print(arr.shape,"\n")
print(arr)

(2, 3, 4) 

(3, 4, 2) 

[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [11]:
import numpy as np
arr = np.array([
    [1,2,3,np.nan,5],
    [np.nan, -2, 5, 0,-7]
])

print(arr,"\n")

col_mean = np.nanmean(arr, axis=0)
inds = np.where(np.isnan(arr))
arr[inds] = np.take(col_mean, inds[1])
print(arr)

[[ 1.  2.  3. nan  5.]
 [nan -2.  5.  0. -7.]] 

[[ 1.  2.  3.  0.  5.]
 [ 1. -2.  5.  0. -7.]]


In [12]:
import numpy as np
arr = np.array([10,-20,30,-40,50])
arr[arr<0] = 0
print(arr)

[10  0 30  0 50]


In [ ]:
import numpy as np
arr1 = np.array([[3, 4],[1,2]]) 
arr2 = np.array([[1, 0],[7,8]])
avg = (arr1 + arr2)/2
print("Average of NumPy arrays:\n", avg)


comb = np.concatenate((arr1.flatten(),
                           arr2.flatten())) 


print("Mean:", np.mean(comb))
print("Median:", np.median(comb))
print("Mode:", np.mod(comb))

Average of NumPy arrays:
 [[2. 2.]
 [4. 5.]]
Mean: 3.25
Median: 2.5


TypeError: remainder() takes from 2 to 3 positional arguments but 1 was given

In [ ]:
import numpy as np

a = np.array([
    [1,-2,3],
    [-1,3,-1],
    [2,-5,5]
])
b = np.array([9,-6,17])
X1 = np.linalg.solve(a,b)
print(X1)

a_inv = np.linalg.inv(a)

X2 = np.dot(a_inv,b)

print(X2)

[ 1. -1.  2.]
[ 1. -1.  2.]
