In [ ]:
# 1) Replace Nan with 0 and Interchange 3 rows and 3 columns of 2D array [[6, -8, 73, -110], [np.nan, -8, 0, 94]] 
# 2) Move axes of 3D array to new positions 
# 3) Replace NaN values with average of columns 
# 4) Replace negative value with zero in numpy array using replace

In [ ]:
import numpy as np

a = np.array([
    [1,2,3,4],
    [np.nan,6,7,8]
])
print("\nOriginal array:\n",a)

a = np.nan_to_num(a,nan=0)
print("\nReplacing array:\n",a)

b=a.T
print("\nTranspose Array:\n",b)


Original array:
 [[ 1.  2.  3.  4.]
 [nan  6.  7.  8.]]

Replacing array:
 [[1. 2. 3. 4.]
 [0. 6. 7. 8.]]

Transpose Array:
 [[1. 0.]
 [2. 6.]
 [3. 7.]
 [4. 8.]]


In [ ]:
import numpy as np

a = np.arange(24).reshape(2,3,4)

print("\nOriginal Shape:\n",a.shape)
print(a)

b = np.moveaxis(a,0,2)
print("\nNew Shape:\n",b.shape)


Original Shape:
 (2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

New Shape:
 (3, 4, 2)


In [ ]:
import numpy as np

a = np.array([
    [1,2,4],
    [np.nan,6,7],
    [7,8,np.nan]
])
print("\nOriginal array:\n",a)

col = np.nanmean(a, axis=0)
print("\ncolumn mean:\n", col)

inds = np.where(np.isnan(a))
a[inds] = np.take(col, inds[1])
print("\nArray:\n", a)


Original array:
 [[ 1.  2.  4.]
 [nan  6.  7.]
 [ 7.  8. nan]]

column mean:
 [4.         5.33333333 5.5       ]

Array:
 [[1.  2.  4. ]
 [4.  6.  7. ]
 [7.  8.  5.5]]


In [13]:
import numpy as np

a = np.array([2, -5, 7, -9, 10, -1])
print("Original Array:", a)

a[a<0] = 0
print("Updated Array:", a)




Original Array: [ 2 -5  7 -9 10 -1]
Updated Array: [ 2  0  7  0 10  0]
