In [ ]:
# 1) Create numpy array and perform following operation 
# > Convert 1D array to 2D
#  > Print Array Attributes(Like shape, dimenssion, data type, itemsize) 
#  > Create a 3×3 NumPy array of all 9 
# > Create a 1D array of 10 evenly spaced values between 25 and 125 
#  > Convert a Python list into a NumPy array
# > Reverse a 1D NumPy array 
# > Create a 4×4×3 array and extract value at its second set, first row and last column 
# > Create a 4×4 and Extract Odd Rows and Even Columns 
# > Slice the first two rows and first two columns of econd set from a 4×4×3 array
#  > Replace all odd numbers in a NumPy array with -1 by itterating using for loop [[23, 56, 78, 93], [71, 82,13, 24]]
#  > Get the indices of non-zero elements in an array [1, 0, 2, 0, 3, 0, 4] 
# > Perform arithmetic operations on two NumPy arrays element-wise Add two NumPy arrays element by element. Multiply two NumPy arrays element by element. 
# > Write a code to compute the dot product of two NumPy arrays arr1 = [15, 20, 25] arr2 = [10,40,37]

In [ ]:
# > Convert 1D array to 2D
import numpy as np
a1 = np.array([1,2,3,4,5,6])
a2 = a1.reshape(2,3)
print(a1)
print(a2)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
#  > Print Array Attributes(Like shape, dimenssion, data type, itemsize) 
print(("Shape:",a2.shape))
print(("Dimension:",a2.ndim))
print(("Data Type:",a2.dtype))
print(("Item Size:",a2.itemsize, "bytes"))

('Shape:', (2, 3))
('Dimension:', 2)
('Data Type:', dtype('int64'))
('Item Size:', 8, 'bytes')


In [ ]:
#  > Create a 3×3 NumPy array of all 9 
a3 = np.full((3,3),9)
print(a3)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [ ]:
# > Create a 1D array of 10 evenly spaced values between 25 and 125 
a4 = np.linspace(25, 125, 10)
print(a4)

[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]


In [ ]:
#  > Convert a Python list into a NumPy array
py_list = [1,2,3,4,5]
a5 = np.array(py_list)
print(a5)

[1 2 3 4 5]


In [ ]:
# > Reverse a 1D NumPy array 
arr = np.array([1,2,3,4,5,6])
reverse_arr = arr[-1::-1]
print(arr)
print(reverse_arr)


[1 2 3 4 5 6]
[6 5 4 3 2 1]


In [56]:
# > Create a 4×4×3 array and extract value at its second set, first row and last column 
arr1 = np.arange(48).reshape(4,4,3)
print(arr1)
x = arr1[1,0,2]
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]
14


In [ ]:
# > Create a 4×4 and Extract Odd Rows and Even Columns 
arr2 = np.arange(1,17).reshape(4, 4)
print(arr2,"\n")
res = arr2[1::2, ::2]
print(res)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[[ 5  7]
 [13 15]]


In [ ]:
# > Slice the first two rows and first two columns of econd set from a 4×4×3 array
arr1 = np.arange(48).reshape(4,4,3)
print(arr1,"\n")
slice_arr = arr1[1, :2, :2]
print(slice_arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]] 

[[12 13]
 [15 16]]


In [ ]:
#  > Replace all odd numbers in a NumPy array with -1 by itterating using for loop [[23, 56, 78, 93], [71, 82,13, 24]]
arr3 = np.array([[1,2,3,4],
                 [6,7,8,9]])
print(arr3,"\n")

for i in range(arr3.shape[0]):
    for j in range(arr3.shape[1]):
        if arr3[i,j] % 2 != 0:
            arr3[i, j] = -1
print(arr3)


[[1 2 3 4]
 [6 7 8 9]] 

[[-1  2 -1  4]
 [ 6 -1  8 -1]]


In [ ]:
#  > Get the indices of non-zero elements in an array [1, 0, 2, 0, 3, 0, 4] 
arr4 = np.array([1,2,3,4,5])
print(arr4)
indices = np.nonzero(arr4)
print(indices)

[1 2 3 4 5]
(array([0, 1, 2, 3, 4]),)


In [ ]:
# > Perform arithmetic operations on two NumPy arrays element-wise Add two NumPy arrays element by element.#  Multiply two NumPy arrays element by element.
a = np.array([10,20,30])
b = np.array([40,50,60])
print("Addition:",a + b)
print("Multiplication:", a * b)


Addition: [50 70 90]
Multiplication: [ 400 1000 1800]


In [ ]:
# > Write a code to compute the dot product of two NumPy arrays arr1 = [15, 20, 25] arr2 = [10,40,37]
a = np.array([10,20,30])
b = np.array([40,50,60])
dot_product = np.dot(a,b)
print(dot_product)

3200
